### ISSUE TITLE
golangの実行環境構築

### ISSUE THREAD

**Issue by 3-yuma-3** [op19-it-edu/api-server#11]

**Comment by ktngch** [comment]
このissueは対応するbranchが存在しないと思いますが、closeの条件としては「3人がそれぞれ、golangとmysqlの実行環境を作る」でという認識で大丈夫でしょうか？

**Comment by 3-yuma-3** [comment]
「新規ブランチを切って、 `Hellow, World` が返ってくる `main.go` ファイルを作成する。」がゴールかなと思ってました。  
レビュー時に他の二人の環境でも動くことが確かめられれば、そのブランチをmasterにmergeして  
その後にControllerかModelを作り始めるブランチで、 `main.go` から `Hellow, World` を消すのはいかがでしょう？  
MySQLについてはgormの導入時にやるイメージでした。

**Comment by ktngch** [comment]
> 「新規ブランチを切って、 `Hellow, World` が返ってくる `main.go` ファイルを作成する。」がゴールかなと思ってました。
> レビュー時に他の二人の環境でも動くことが確かめられれば、そのブランチをmasterにmergeして
> その後にControllerかModelを作り始めるブランチで、 `main.go` から `Hellow, World` を消すのはいかがでしょう？

okです、流れ理解しました（実行環境ができているか確認する用にブランチ（ソースコード）を用意して、PRをその確認の場として使うイメージですね）

> MySQLについてはgormの導入時にやるイメージでした。

少し話がそれますが、簡単化と環境差分を排除するために、DB作成用のDockerfileを作成する予定なんですが、その実行テストを別でissueに切ってもいいかなと思いますがどうでしょう？（DB <-> gormの連携はまた別のissueとして対応）

**Comment by 3-yuma-3** [comment]
> DB作成用のDockerfile

めっちゃ助かります。  
Issue化お願いします。  
思い思いにIssue切って、必要性と中身の詳細についてはcommentでしていけばいいかなと思います。

**Comment by ktngch** [comment]
> Issue化お願いします。

了解ですん
mysql用の名前空間確保のために、このissueの名前を「golangの実行環境構築」のようにリネームしてもらっていいですか？

**Comment by 3-yuma-3** [comment]
リネームしましたー

**Comment by ktngch** [comment]
mysqlの環境構築、issue化してます
