### ISSUE TITLE
開発用DBの実行環境構築

### ISSUE THREAD

**Issue by ktngch** [op19-it-edu/api-server#15]
- DB作成用の`Dockerfile`（と`docker-compose.yml`）とコンテナ起動コマンド用のシェルスクリプトを作成する
  - 目的
    - OSやmysqlのバージョン等の環境差分の排除
    - 簡単化
- 実行可能かをPR内で確認する

**Comment by ktngch** [comment]
[このブランチ](https://github.com/op19-it-edu/api-server/tree/add_db_setup_dir)で対応済です。現在PRを出している #16 #17 がmergeされ次第、rebaseしてこちらのブランチもPRに出す予定です

**Comment by xinxin-pipa** [comment]
rebaseについて調べましたが、要するに、Mergeで省略されたcommit logも含めて、開発過程でのcommitを綺麗に整理しましょうって言う理解で合ってます？

**Comment by ktngch** [comment]
ブランチを切ったときよりもmasterが進んでしまったときに、rebaseすると、最新のmasterを起点にブランチを付け替えることができます
参考↓
http://kik.xii.jp/archives/117

**Comment by ktngch** [comment]
↓これめちゃわかりすいです
https://kray.jp/blog/git-pull-rebase/

**Comment by xinxin-pipa** [comment]
>↓これめちゃわかりすいです
https://kray.jp/blog/git-pull-rebase/

可愛く楽しく理解できました。
